### ISSUE TITLE
What's python-telegram-bot version

### ISSUE THREAD

**Issue by muji92** [nobrainghost/flash-usdt-sender#1]
![Screenshot_2024-10-27-15-47-22-370_com termux](https://github.com/user-attachments/assets/992998a9-f383-4359-a7eb-2883377049b5)

**Comment by nobrainghost** [comment]
Use python-telegram-bot 13.7 and urlllib3-1.26.15
pip uninstall python-telegram-bot urllib3
pip install urllib3==1.26.15 (install this first)
pip install python-telegram-bot==13.7

**Comment by muji92** [comment]
Still loading not show anything 
![Screenshot_2024-10-27-21-41-47-771_com termux](https://github.com/user-attachments/assets/374067c6-c4d6-47fc-aca8-de18cbe13ee8)
